#!/usr/bin/env python3
# Generira en/index.html i de/index.html iz HR index.html.
# Svaki par (hr -> prijevod) MORA pogoditi bar jednom, inače skripta pukne.
import sys, os, re

ROOT = "/Users/vajda/web_stranice/BARE/final bare/v5"
src = open(os.path.join(ROOT, "index.html"), encoding="utf-8").read()

SWITCH_HR = '<a href="./" aria-current="page" lang="hr" hreflang="hr" aria-label="Hrvatski">HR</a><span class="sep" aria-hidden="true">|</span><a href="en/" lang="en" hreflang="en" aria-label="English">EN</a><span class="sep" aria-hidden="true">|</span><a href="de/" lang="de" hreflang="de" aria-label="Deutsch">DE</a>'
SWITCH_EN = '<a href="../" lang="hr" hreflang="hr" aria-label="Hrvatski">HR</a><span class="sep" aria-hidden="true">|</span><a href="./" aria-current="page" lang="en" hreflang="en" aria-label="English">EN</a><span class="sep" aria-hidden="true">|</span><a href="../de/" lang="de" hreflang="de" aria-label="Deutsch">DE</a>'
SWITCH_DE = '<a href="../" lang="hr" hreflang="hr" aria-label="Hrvatski">HR</a><span class="sep" aria-hidden="true">|</span><a href="../en/" lang="en" hreflang="en" aria-label="English">EN</a><span class="sep" aria-hidden="true">|</span><a href="./" aria-current="page" lang="de" hreflang="de" aria-label="Deutsch">DE</a>'

COMMON_PATHS = [
    ('src="assets/', 'src="../assets/'),
    ('srcset="assets/', 'srcset="../assets/'),
    (', assets/', ', ../assets/'),
    ('poster="assets/', 'poster="../assets/'),
    ('href="assets/', 'href="../assets/'),
    ('src="hero.jpg"', 'src="../hero.jpg"'),
    ('src="story.jpg"', 'src="../story.jpg"'),
]

EN = [
    ('<html lang="hr">', '<html lang="en">'),
    ('<title>Konoba Bare — Prvić Šepurine | Otok Prvić</title>',
     '<title>Konoba Bare — Prvić Šepurine | Prvić Island, Croatia</title>'),
    ('<meta name="description" content="Konoba Bare na otoku Prviću, u Prvić Šepurinama. Otočka dalmatinska kuhinja: hladne plate mora, hobotnica ispod peke, pizza s terase uz more. Brod Bare za uvale Prvića, na upit." />',
     '<meta name="description" content="Konoba Bare on Prvić Island, in Prvić Šepurine, Croatia. Island Dalmatian cooking: cold seafood platters, octopus under the peka (iron bell), pizza on a terrace by the sea. Boat Bare for the island coves, on request." />'),
    ('<link rel="canonical" href="https://artme-nx.github.io/konoba-bare-v5/" />',
     '<link rel="canonical" href="https://artme-nx.github.io/konoba-bare-v5/en/" />'),
    ('<meta property="og:title" content="Konoba Bare — Prvić Šepurine, otok Prvić" />',
     '<meta property="og:title" content="Konoba Bare — Prvić Šepurine, Prvić Island" />'),
    ('<meta property="og:description" content="Otočka dalmatinska konoba u Prvić Šepurinama: hladne plate mora, peka na narudžbu, pizza uz more. Brod Bare za skrivene uvale, na upit." />',
     '<meta property="og:description" content="An island Dalmatian konoba in Prvić Šepurine: cold seafood platters, peka to order, pizza by the sea. Boat Bare for hidden coves, on request." />'),
    ('<meta property="og:url" content="https://artme-nx.github.io/konoba-bare-v5/" />',
     '<meta property="og:url" content="https://artme-nx.github.io/konoba-bare-v5/en/" />'),
    ('<meta property="og:locale" content="hr_HR" />', '<meta property="og:locale" content="en_GB" />'),
    ('"url": "https://artme-nx.github.io/konoba-bare-v5/",', '"url": "https://artme-nx.github.io/konoba-bare-v5/en/",'),
    ('"servesCuisine": ["Dalmatinska", "Mediteranska"],', '"servesCuisine": ["Dalmatian", "Mediterranean"],'),
    ('<a class="skip" href="#main">Preskoči na sadržaj</a>', '<a class="skip" href="#main">Skip to content</a>'),
    ('Bare<small>Konoba · Otok Prvić</small>', 'Bare<small>Konoba · Prvić Island</small>'),
    ('>Naša priča</a>', '>Our story</a>'),
    ('>Jelovnik</a>', '>Menu</a>'),
    ('>Galerija</a>', '>Gallery</a>'),
    ('>Najam broda</a>', '>Boat rental</a>'),
    ('>Kako doći</a>', '>Getting here</a>'),
    ('class="btn-res">Rezerviraj stol</a>', 'class="btn-res">Book a table</a>'),
    (SWITCH_HR, SWITCH_EN),
    ('aria-label="Odabir jezika"', 'aria-label="Choose language"'),
    ('aria-label="Izbornik"', 'aria-label="Menu"'),
    ('aria-label="Zatvori izbornik"', 'aria-label="Close menu"'),
    ('class="btn-res">Nazovi za stol · 022 448 094</a>', 'class="btn-res">Call for a table · 022 448 094</a>'),
    ('aria-label="Nazovi konobu Bare · 022 448 094"', 'aria-label="Call Konoba Bare · 022 448 094"'),
    ('alt="Prvić Šepurine iz zraka — otočka luka, kamene kuće i more, otok Prvić"',
     'alt="Prvić Šepurine from the air: the island harbour, stone houses and the sea, Prvić Island"'),
    ('<span class="eyebrow">Prvić Šepurine · Šibenski arhipelag</span>', '<span class="eyebrow">Prvić Šepurine · Šibenik archipelago</span>'),
    ('<p class="tag">Otok na kojem vrijeme sporije teče</p>', '<p class="tag">An island where time moves more slowly</p>'),
    ('<div class="scroll-ind">Polako<span class="line"></span></div>', '<div class="scroll-ind">Take it slow<span class="line"></span></div>'),
    ('aria-label="Otok Prvić u četiri činjenice"', 'aria-label="Prvić Island in four facts"'),
    ('<span class="stat-label">automobila</span>', '<span class="stat-label">cars</span>'),
    ('<span class="stat-label">minuta od Vodica</span>', '<span class="stat-label">minutes from Vodice</span>'),
    ('<span class="stat-word">Zaštićena hrvatska baština</span>', '<span class="stat-word">Protected Croatian heritage</span>'),
    ('<span class="stat-word">Dom Fausta Vrančića</span>', '<span class="stat-word">Home of Faust Vrančić</span>'),
    ('<h2>Jelovnik</h2>', '<h2>Menu</h2>'),
    ('<h3 class="part-title">Pizze</h3>', '<h3 class="part-title">Pizzas</h3>'),
    ('<p class="part-note">Iz peći, na terasi uz more</p>', '<p class="part-note">From the oven, on the terrace by the sea</p>'),
    ('<li>Sir–šunka</li>', '<li>Sir–šunka<small>cheese &amp; ham</small></li>'),
    ('<li>Miješana</li>', '<li>Miješana<small>mixed</small></li>'),
    ('<li>Sir–gljive</li>', '<li>Sir–gljive<small>cheese &amp; mushrooms</small></li>'),
    ('<li>Pikant</li>', '<li>Pikant<small>spicy</small></li>'),
    ('<li>4 vrste sira</li>', '<li>4 vrste sira<small>four cheeses</small></li>'),
    ('<li>Seljačka</li>', '<li>Seljačka<small>country-style</small></li>'),
    ('<li>4 godišnja doba</li>', '<li>4 godišnja doba<small>four seasons</small></li>'),
    ('<li>Vegetarijana</li>', '<li>Vegetarijana<small>vegetarian</small></li>'),
    ('<li>Tuna</li>', '<li>Tuna<small>tuna</small></li>'),
    ('<h3 class="part-title">Iz konobe</h3>', '<h3 class="part-title">From the konoba</h3>'),
    ('<li>Hladna plata</li>', '<li>Hladna plata<small>cold seafood platter</small></li>'),
    ('<li>Dimljena tuna</li>', '<li>Dimljena tuna<small>smoked tuna</small></li>'),
    ('<li>Slane srdele</li>', '<li>Slane srdele<small>salt-cured sardines</small></li>'),
    ('<li>Kuhana sabljarka</li>', '<li>Kuhana sabljarka<small>poached swordfish</small></li>'),
    ('<li>Pršut i sir</li>', '<li>Pršut i sir<small>prosciutto &amp; cheese</small></li>'),
    ('<li>Pašteta od tune</li>', '<li>Pašteta od tune<small>tuna pâté</small></li>'),
    ('<li>Salate</li>', '<li>Salate<small>salads</small></li>'),
    ('<p class="peka-note">na narudžbu, dan ranije</p>', '<p class="peka-note">under the iron bell · to order, a day ahead</p>'),
    ('<li>— Meso</li>', '<li>— Meso (meat)</li>'),
    ('<li>— Hobotnica</li>', '<li>— Hobotnica (octopus)</li>'),
    ('aria-label="Otkrivanje peke"', 'aria-label="Lifting the peka"'),
    ('<span class="eyebrow t-reveal">Naša priča</span>', '<span class="eyebrow t-reveal">Our story</span>'),
    ('<h2>Otok na kojem je vrijeme stalo</h2>', '<h2>The island where time stands still</h2>'),
    ('<p data-words>Već u srednjem vijeku Prvić je bio utočište šibenske aristokracije: mjesto kamo se bježalo od gradske vreve i od kuge s kopna. Plemićke obitelji Tavelić, Divnić, Šižgorić i Draganić-Vrančić gradile su ovdje ljetnikovce, a renesansni dvor obitelji Draganić-Vrančić stoji u Šepurinama i danas.</p>',
     '<p data-words>As early as the Middle Ages, Prvić was a refuge for the aristocracy of Šibenik: a place to escape the bustle of the city and the plague on the mainland. The noble families Tavelić, Divnić, Šižgorić and Draganić-Vrančić built their summer villas here, and the Renaissance manor of the Draganić-Vrančić family still stands in Šepurine today.</p>'),
    ('<p data-words>Stoljećima kasnije otok radi po istom receptu: strme kalete, zvono crkve i more koje sve nadglasava. Ovdje se ne dolazi slučajno. Dolazi se jer se traži upravo ovaj mir.</p>',
     '<p data-words>Centuries later, the island still works to the same recipe: steep lanes, the church bell, and a sea that outvoices them all. Nobody ends up here by accident. You come because you are looking for exactly this kind of peace.</p>'),
    ('<p data-words>Bare je obiteljska konoba, ovdje od 2008. Kroz cijelu godinu vrata su otvorena kao caffe bar, mjesto gdje otok uspori uz kavu i more pred sobom. Ljeti postajemo konoba i pizzeria, za stolove pune gostiju koji su brodom Lara doplovili po taj isti mir.</p>',
     '<p data-words>Bare is a family konoba, here since 2008. All year round the doors are open as a café bar, a place where the island slows down over coffee with the sea in front of it. In summer we become a konoba and pizzeria, with tables full of guests who sailed over on the Lara boat line looking for that same peace.</p>'),
    ('<p data-words>Na stolu su hladne plate mora: slane srdele, dimljena tuna, kuhana sabljarka i domaća pašteta od tune, uz pršut, sir i masline. Hobotnicu i meso ispod peke spremamo na narudžbu, dan ranije, jer dobre stvari ovdje znaju pričekati. A za dulji stol i cijelu obitelj, tu je i pizza.</p>',
     '<p data-words>On the table are cold platters of the sea: salt-cured sardines, smoked tuna, poached swordfish and our homemade tuna pâté, alongside prosciutto, cheese and olives. Octopus and meat ispod peke (under the iron bell) are prepared to order, a day ahead, because good things here are worth waiting for. And for a longer table and the whole family, there is pizza.</p>'),
    ('<p class="sig" data-words>Dobrodošli u našu konobu — i u naš otok.</p>',
     '<p class="sig" data-words>Welcome to our konoba, and to our island.</p>'),
    ('alt="Kameni trg Prvić Šepurina s crkvom, maslinom i terasom konobe Bare"',
     'alt="The stone square of Prvić Šepurine with the church, an olive tree and the terrace of Konoba Bare"'),
    ('alt="Zalazak sunca nad morem i kamenim mulom kraj Prvić Šepurina"',
     'alt="Sunset over the sea and the stone pier near Prvić Šepurine"'),
    ('<span class="eyebrow reveal">Galerija</span>', '<span class="eyebrow reveal">Gallery</span>'),
    ('<h2>S peke i iz kuhinje</h2>', '<h2>From the peka and the kitchen</h2>'),
    ('alt="Hobotnica ispod peke s krumpirom, u teći konobe Bare"', 'alt="Octopus under the peka with potatoes, in the pan at Konoba Bare"'),
    ('<figcaption>Hobotnica ispod peke</figcaption>', '<figcaption>Octopus under the peka</figcaption>'),
    ('alt="Hladne plate mora s paštetom od tune, maslinama i domaćim kruhom"', 'alt="Cold seafood platters with tuna pâté, olives and homemade bread"'),
    ('<figcaption>Hladna plata</figcaption>', '<figcaption>The cold platter</figcaption>'),
    ('alt="Meso ispod peke s krumpirom u teći, žeravica u pozadini"', 'alt="Meat under the peka with potatoes in the pan, embers in the background"'),
    ('<figcaption>Meso ispod peke</figcaption>', '<figcaption>Meat under the peka</figcaption>'),
    ('alt="Vatra od drva za peku u konobi Bare"', 'alt="Wood fire for the peka at Konoba Bare"'),
    ('<figcaption>Vatra od drva</figcaption>', '<figcaption>Wood fire</figcaption>'),
    ('alt="Plamen nad gradelama i žeravica uz peke u konobi Bare"', 'alt="Flames over the grill and embers beside the peka bells at Konoba Bare"'),
    ('<figcaption>Žar i gradele</figcaption>', '<figcaption>Embers and the grill</figcaption>'),
    ('alt="Pizza iz konobe Bare, ravno iz peći"', 'alt="Pizza from Konoba Bare, straight from the oven"'),
    ('<figcaption>Pizza za cijeli stol</figcaption>', '<figcaption>Pizza for the whole table</figcaption>'),
    ('alt="Krakovi hobotnice s krumpirom izbliza, iz teće"', 'alt="Octopus tentacles with potatoes up close, from the pan"'),
    ('<figcaption>Iz teće</figcaption>', '<figcaption>From the pan</figcaption>'),
    ('alt="Pizza s rukolom na stolu terase konobe Bare"', 'alt="Pizza with rocket on a terrace table at Konoba Bare"'),
    ('<figcaption>Na terasi, uz more</figcaption>', '<figcaption>On the terrace, by the sea</figcaption>'),
    ('aria-label="Video momenti iz kuhinje"', 'aria-label="Video moments from the kitchen"'),
    ('<span class="eyebrow reveal">Iz kuhinje, uživo</span>', '<span class="eyebrow reveal">From the kitchen, live</span>'),
    ('<h2 class="reveal">Tri kadra ispod peke</h2>', '<h2 class="reveal">Three scenes from under the peka</h2>'),
    ('aria-label="Hobotnica ispod peke s krumpirom u teći, dim se diže"', 'aria-label="Octopus under the peka with potatoes in the pan, smoke rising"'),
    ('aria-label="Peka pod žarom, zatim meso s krumpirom u teći"', 'aria-label="The peka bell under embers, then meat with potatoes in the pan"'),
    ('aria-label="Slaganje hladne plate: tuna, masline, kapari i salata od hobotnice"', 'aria-label="Plating the cold platter: tuna, olives, capers and octopus salad"'),
    ('<span class="eyebrow t-reveal">Najam broda · Bare</span>', '<span class="eyebrow t-reveal">Boat rental · Bare</span>'),
    ('<h2>More na dohvat ruke: najam broda</h2>', '<h2>The sea within reach: rent our boat</h2>'),
    ('<p class="lead" data-words>Konoba Bare nije samo stol uz more.</p>', '<p class="lead" data-words>Konoba Bare is more than a table by the sea.</p>'),
    ('<p data-words>Našim brodom Bare istražite skrivene uvale Prvića i okolnih otočića vlastitim ritmom: tiho sidrište za kupanje, ručak na pučini, zalazak daleko od gužve.</p>',
     '<p data-words>Take our boat Bare and explore the hidden coves of Prvić and the surrounding islets at your own pace: a quiet anchorage for a swim, lunch out on the water, a sunset far from the crowds.</p>'),
    ('<p data-words>Detalji plovidbe i cijena: na upit, telefonom ili za stolom u konobi.</p>',
     '<p data-words>Sailing details and price: on request, by phone or at your table in the konoba.</p>'),
    ('class="btn-res t-reveal">Upit za najam · 022 448 094</a>', 'class="btn-res t-reveal">Rental enquiry · 022 448 094</a>'),
    ('<span class="alt-contact" data-words>Ili pitajte konobara kad sljedeći put sjednete: brod je vezan u luci, par koraka od stola.</span>',
     '<span class="alt-contact" data-words>Or simply ask your waiter the next time you sit down: the boat is moored in the harbour, a few steps from your table.</span>'),
    ('alt="Brod Bare usidren u tihoj uvali otoka Prvića, kupači u tirkiznom moru uz borovu obalu"',
     'alt="The boat Bare anchored in a quiet cove of Prvić Island, swimmers in turquoise water along a pine shore"'),
    ('alt="Luka Prvić Šepurina u zlatni sat: barke, kamena kuća i jedrilica u kanalu"',
     'alt="The harbour of Prvić Šepurine at golden hour: small boats, a stone house and a sailboat in the channel"'),
    ('alt="Brod Lara uplovljava u zalazak sunca pred Prvić Šepurinama, uz svjetionik na mulu"',
     'alt="The Lara boat sailing into the sunset off Prvić Šepurine, past the light on the pier"'),
    ('„Večer na Prviću ne traži ništa, samo da ostanete još malo.“',
     '“An evening on Prvić asks for nothing, only that you stay a little longer.”'),
    ('<span class="eyebrow">Kako doći</span>', '<span class="eyebrow">Getting here</span>'),
    ('<h2>Pronađite nas na otoku.</h2>', '<h2>Find us on the island.</h2>'),
    ('<h3>Adresa</h3>', '<h3>Address</h3>'),
    ('<p data-words>Prvić Šepurine, otok Prvić<br/>Šibensko-kninska županija, Hrvatska</p>',
     '<p data-words>Prvić Šepurine, Prvić Island<br/>Šibenik-Knin County, Croatia</p>'),
    ('<h3>Brod Lara</h3>', '<h3>The Lara boat line</h3>'),
    ('<p data-words>Otok Prvić nema automobila. Dolazi se brodom Lara, redovnom brodskom linijom iz Šibenika i Vodica do Prvić Šepurina. Od pristaništa do konobe: kratka šetnja kalama.</p>',
     '<p data-words>The island of Prvić is car-free. You arrive on the Lara boat line, the regular service from Šibenik and Vodice to Prvić Šepurine. From the pier, it is a short walk through the stone lanes to the konoba.</p>'),
    ('<h3>Radno vrijeme</h3>', '<h3>Opening hours</h3>'),
    ('<p data-words>Caffe bar: otvoren cijeli dan.<br/>Kuhinja: 14:00 – 23:00.<br/>Za veće stolove i peku javite se telefonom, uskladit ćemo i s rasporedom broda Lara.</p>',
     '<p data-words>Café bar: open all day.<br/>Kitchen: 14:00 – 23:00.<br/>For larger tables and peka, give us a call, and we will work around the Lara boat timetable too.</p>'),
    ('<h3>Rezervacije</h3>', '<h3>Reservations</h3>'),
    ('<p>Telefon: <a', '<p>Phone: <a'),
    ('style="margin-top:6px">Rezerviraj stol</a>', 'style="margin-top:6px">Book a table</a>'),
    ('<small>Klikom se učitava interaktivna karta s Google Maps servisa. Tek tada Google primi vaš IP.</small>',
     '<small>Clicking loads the interactive Google Maps view. Only then does Google receive your IP address.</small>'),
    ('<span class="btn-res">Prikaži kartu</span>', '<span class="btn-res">Show map</span>'),
    ("f.title='Karta — Konoba Bare, Prvić Šepurine';", "f.title='Map — Konoba Bare, Prvić Šepurine';"),
    ('<p>Otočka konoba u Prvić Šepurinama. Riba, hobotnica i maslinovo ulje, u ritmu otoka bez automobila.</p>',
     '<p>An island konoba in Prvić Šepurine. Fish, octopus and olive oil, in the rhythm of a car-free island.</p>'),
    ('<h3>Stranica</h3>', '<h3>Pages</h3>'),
    ('<a class="fl" href="#prica">Naša priča</a>', '<a class="fl" href="#prica">Our story</a>'),
    ('<a class="fl" href="#menu">Jelovnik</a>', '<a class="fl" href="#menu">Menu</a>'),
    ('<a class="fl" href="#galerija">Galerija</a>', '<a class="fl" href="#galerija">Gallery</a>'),
    ('<a class="fl" href="#najam-broda">Najam broda</a>', '<a class="fl" href="#najam-broda">Boat rental</a>'),
    ('<a class="fl" href="#lokacija">Kako doći</a>', '<a class="fl" href="#lokacija">Getting here</a>'),
    ('<p style="margin-top:8px">Prvić Šepurine<br/>otok Prvić, Hrvatska</p>', '<p style="margin-top:8px">Prvić Šepurine<br/>Prvić Island, Croatia</p>'),
    ('<span>Stranica bez kolačića i analitike. Karta (Google Maps) učitava se tek na vaš klik.</span>',
     '<span>No cookies, no analytics. The map (Google Maps) loads only when you click.</span>'),
]

DE = [
    ('<html lang="hr">', '<html lang="de">'),
    ('<title>Konoba Bare — Prvić Šepurine | Otok Prvić</title>',
     '<title>Konoba Bare — Prvić Šepurine | Insel Prvić, Kroatien</title>'),
    ('<meta name="description" content="Konoba Bare na otoku Prviću, u Prvić Šepurinama. Otočka dalmatinska kuhinja: hladne plate mora, hobotnica ispod peke, pizza s terase uz more. Brod Bare za uvale Prvića, na upit." />',
     '<meta name="description" content="Konoba Bare auf der Insel Prvić, in Prvić Šepurine, Kroatien. Dalmatinische Inselküche: kalte Fischplatten, Oktopus unter der Peka-Glocke, Pizza auf der Terrasse am Meer. Boot Bare für die Buchten der Insel, auf Anfrage." />'),
    ('<link rel="canonical" href="https://artme-nx.github.io/konoba-bare-v5/" />',
     '<link rel="canonical" href="https://artme-nx.github.io/konoba-bare-v5/de/" />'),
    ('<meta property="og:title" content="Konoba Bare — Prvić Šepurine, otok Prvić" />',
     '<meta property="og:title" content="Konoba Bare — Prvić Šepurine, Insel Prvić" />'),
    ('<meta property="og:description" content="Otočka dalmatinska konoba u Prvić Šepurinama: hladne plate mora, peka na narudžbu, pizza uz more. Brod Bare za skrivene uvale, na upit." />',
     '<meta property="og:description" content="Dalmatinische Inselkonoba in Prvić Šepurine: kalte Fischplatten, Peka auf Vorbestellung, Pizza am Meer. Boot Bare für versteckte Buchten, auf Anfrage." />'),
    ('<meta property="og:url" content="https://artme-nx.github.io/konoba-bare-v5/" />',
     '<meta property="og:url" content="https://artme-nx.github.io/konoba-bare-v5/de/" />'),
    ('<meta property="og:locale" content="hr_HR" />', '<meta property="og:locale" content="de_DE" />'),
    ('"url": "https://artme-nx.github.io/konoba-bare-v5/",', '"url": "https://artme-nx.github.io/konoba-bare-v5/de/",'),
    ('"servesCuisine": ["Dalmatinska", "Mediteranska"],', '"servesCuisine": ["Dalmatinisch", "Mediterran"],'),
    ('<a class="skip" href="#main">Preskoči na sadržaj</a>', '<a class="skip" href="#main">Zum Inhalt springen</a>'),
    ('Bare<small>Konoba · Otok Prvić</small>', 'Bare<small>Konoba · Insel Prvić</small>'),
    ('>Naša priča</a>', '>Unsere Geschichte</a>'),
    ('>Jelovnik</a>', '>Speisekarte</a>'),
    ('>Galerija</a>', '>Galerie</a>'),
    ('>Najam broda</a>', '>Bootsverleih</a>'),
    ('>Kako doći</a>', '>Anreise</a>'),
    ('class="btn-res">Rezerviraj stol</a>', 'class="btn-res">Tisch reservieren</a>'),
    (SWITCH_HR, SWITCH_DE),
    ('aria-label="Odabir jezika"', 'aria-label="Sprache wählen"'),
    ('aria-label="Izbornik"', 'aria-label="Menü"'),
    ('aria-label="Zatvori izbornik"', 'aria-label="Menü schließen"'),
    ('class="btn-res">Nazovi za stol · 022 448 094</a>', 'class="btn-res">Anrufen &amp; reservieren · 022 448 094</a>'),
    ('aria-label="Nazovi konobu Bare · 022 448 094"', 'aria-label="Konoba Bare anrufen · 022 448 094"'),
    ('alt="Prvić Šepurine iz zraka — otočka luka, kamene kuće i more, otok Prvić"',
     'alt="Prvić Šepurine aus der Luft: Inselhafen, Steinhäuser und das Meer, Insel Prvić"'),
    ('<span class="eyebrow">Prvić Šepurine · Šibenski arhipelag</span>', '<span class="eyebrow">Prvić Šepurine · Šibeniker Archipel</span>'),
    ('<p class="tag">Otok na kojem vrijeme sporije teče</p>', '<p class="tag">Eine Insel, auf der die Zeit langsamer vergeht</p>'),
    ('<div class="scroll-ind">Polako<span class="line"></span></div>', '<div class="scroll-ind">Ganz langsam<span class="line"></span></div>'),
    ('aria-label="Otok Prvić u četiri činjenice"', 'aria-label="Die Insel Prvić in vier Fakten"'),
    ('<span class="stat-label">automobila</span>', '<span class="stat-label">Autos</span>'),
    ('<span class="stat-label">minuta od Vodica</span>', '<span class="stat-label">Minuten von Vodice</span>'),
    ('<span class="stat-word">Zaštićena hrvatska baština</span>', '<span class="stat-word">Geschütztes kroatisches Erbe</span>'),
    ('<span class="stat-word">Dom Fausta Vrančića</span>', '<span class="stat-word">Heimat von Faust Vrančić</span>'),
    ('<h2>Jelovnik</h2>', '<h2>Speisekarte</h2>'),
    ('<h3 class="part-title">Pizze</h3>', '<h3 class="part-title">Pizzen</h3>'),
    ('<p class="part-note">Iz peći, na terasi uz more</p>', '<p class="part-note">Aus dem Ofen, auf der Terrasse am Meer</p>'),
    ('<li>Sir–šunka</li>', '<li>Sir–šunka<small>Käse &amp; Schinken</small></li>'),
    ('<li>Miješana</li>', '<li>Miješana<small>gemischt</small></li>'),
    ('<li>Sir–gljive</li>', '<li>Sir–gljive<small>Käse &amp; Champignons</small></li>'),
    ('<li>4 vrste sira</li>', '<li>4 vrste sira<small>vier Käsesorten</small></li>'),
    ('<li>Seljačka</li>', '<li>Seljačka<small>nach Bauernart</small></li>'),
    ('<li>4 godišnja doba</li>', '<li>4 godišnja doba<small>vier Jahreszeiten</small></li>'),
    ('<li>Vegetarijana</li>', '<li>Vegetarijana<small>vegetarisch</small></li>'),
    ('<li>Tuna</li>', '<li>Tuna<small>Thunfisch</small></li>'),
    ('<h3 class="part-title">Iz konobe</h3>', '<h3 class="part-title">Aus der Konoba</h3>'),
    ('<li>Hladna plata</li>', '<li>Hladna plata<small>kalte Fischplatte</small></li>'),
    ('<li>Dimljena tuna</li>', '<li>Dimljena tuna<small>geräucherter Thunfisch</small></li>'),
    ('<li>Slane srdele</li>', '<li>Slane srdele<small>gesalzene Sardinen</small></li>'),
    ('<li>Kuhana sabljarka</li>', '<li>Kuhana sabljarka<small>gekochter Schwertfisch</small></li>'),
    ('<li>Pršut i sir</li>', '<li>Pršut i sir<small>Rohschinken &amp; Käse</small></li>'),
    ('<li>Pašteta od tune</li>', '<li>Pašteta od tune<small>Thunfischpastete</small></li>'),
    ('<li>Salate</li>', '<li>Salate<small>Salate</small></li>'),
    ('<p class="peka-note">na narudžbu, dan ranije</p>', '<p class="peka-note">unter der Peka-Glocke · auf Vorbestellung, einen Tag im Voraus</p>'),
    ('<li>— Meso</li>', '<li>— Meso (Fleisch)</li>'),
    ('<li>— Hobotnica</li>', '<li>— Hobotnica (Oktopus)</li>'),
    ('aria-label="Otkrivanje peke"', 'aria-label="Die Peka wird geöffnet"'),
    ('<span class="eyebrow t-reveal">Naša priča</span>', '<span class="eyebrow t-reveal">Unsere Geschichte</span>'),
    ('<h2>Otok na kojem je vrijeme stalo</h2>', '<h2>Die Insel, auf der die Zeit stehen geblieben ist</h2>'),
    ('<p data-words>Već u srednjem vijeku Prvić je bio utočište šibenske aristokracije: mjesto kamo se bježalo od gradske vreve i od kuge s kopna. Plemićke obitelji Tavelić, Divnić, Šižgorić i Draganić-Vrančić gradile su ovdje ljetnikovce, a renesansni dvor obitelji Draganić-Vrančić stoji u Šepurinama i danas.</p>',
     '<p data-words>Schon im Mittelalter war Prvić ein Rückzugsort des Adels von Šibenik: ein Ort, an den man vor dem Trubel der Stadt und der Pest auf dem Festland floh. Die Adelsfamilien Tavelić, Divnić, Šižgorić und Draganić-Vrančić bauten hier ihre Sommerresidenzen, und der Renaissancesitz der Familie Draganić-Vrančić steht bis heute in Šepurine.</p>'),
    ('<p data-words>Stoljećima kasnije otok radi po istom receptu: strme kalete, zvono crkve i more koje sve nadglasava. Ovdje se ne dolazi slučajno. Dolazi se jer se traži upravo ovaj mir.</p>',
     '<p data-words>Jahrhunderte später funktioniert die Insel noch immer nach demselben Rezept: steile Gassen, die Kirchenglocke und ein Meer, das alles übertönt. Hierher kommt niemand zufällig. Man kommt, weil man genau diese Ruhe sucht.</p>'),
    ('<p data-words>Bare je obiteljska konoba, ovdje od 2008. Kroz cijelu godinu vrata su otvorena kao caffe bar, mjesto gdje otok uspori uz kavu i more pred sobom. Ljeti postajemo konoba i pizzeria, za stolove pune gostiju koji su brodom Lara doplovili po taj isti mir.</p>',
     '<p data-words>Bare ist eine Familienkonoba, hier seit 2008. Das ganze Jahr über sind die Türen als Café-Bar geöffnet, ein Ort, an dem die Insel bei einem Kaffee mit Blick aufs Meer langsamer wird. Im Sommer werden wir zur Konoba und Pizzeria, mit Tischen voller Gäste, die mit der Bootslinie Lara gekommen sind, um genau diese Ruhe zu finden.</p>'),
    ('<p data-words>Na stolu su hladne plate mora: slane srdele, dimljena tuna, kuhana sabljarka i domaća pašteta od tune, uz pršut, sir i masline. Hobotnicu i meso ispod peke spremamo na narudžbu, dan ranije, jer dobre stvari ovdje znaju pričekati. A za dulji stol i cijelu obitelj, tu je i pizza.</p>',
     '<p data-words>Auf dem Tisch stehen kalte Platten aus dem Meer: gesalzene Sardinen, geräucherter Thunfisch, gekochter Schwertfisch und hausgemachte Thunfischpastete, dazu Rohschinken, Käse und Oliven. Oktopus und Fleisch ispod peke (unter der Peka-Glocke) bereiten wir auf Vorbestellung zu, einen Tag im Voraus, denn auf gute Dinge wartet man hier gern. Und für die lange Tafel und die ganze Familie gibt es Pizza.</p>'),
    ('<p class="sig" data-words>Dobrodošli u našu konobu — i u naš otok.</p>',
     '<p class="sig" data-words>Willkommen in unserer Konoba, und auf unserer Insel.</p>'),
    ('alt="Kameni trg Prvić Šepurina s crkvom, maslinom i terasom konobe Bare"',
     'alt="Der Steinplatz von Prvić Šepurine mit Kirche, Olivenbaum und der Terrasse der Konoba Bare"'),
    ('alt="Zalazak sunca nad morem i kamenim mulom kraj Prvić Šepurina"',
     'alt="Sonnenuntergang über dem Meer und der Steinmole bei Prvić Šepurine"'),
    ('<span class="eyebrow reveal">Galerija</span>', '<span class="eyebrow reveal">Galerie</span>'),
    ('<h2>S peke i iz kuhinje</h2>', '<h2>Von der Peka und aus der Küche</h2>'),
    ('alt="Hobotnica ispod peke s krumpirom, u teći konobe Bare"', 'alt="Oktopus unter der Peka mit Kartoffeln, in der Pfanne der Konoba Bare"'),
    ('<figcaption>Hobotnica ispod peke</figcaption>', '<figcaption>Oktopus unter der Peka</figcaption>'),
    ('alt="Hladne plate mora s paštetom od tune, maslinama i domaćim kruhom"', 'alt="Kalte Fischplatten mit Thunfischpastete, Oliven und hausgemachtem Brot"'),
    ('<figcaption>Hladna plata</figcaption>', '<figcaption>Kalte Platte</figcaption>'),
    ('alt="Meso ispod peke s krumpirom u teći, žeravica u pozadini"', 'alt="Fleisch unter der Peka mit Kartoffeln in der Pfanne, Glut im Hintergrund"'),
    ('<figcaption>Meso ispod peke</figcaption>', '<figcaption>Fleisch unter der Peka</figcaption>'),
    ('alt="Vatra od drva za peku u konobi Bare"', 'alt="Holzfeuer für die Peka in der Konoba Bare"'),
    ('<figcaption>Vatra od drva</figcaption>', '<figcaption>Holzfeuer</figcaption>'),
    ('alt="Plamen nad gradelama i žeravica uz peke u konobi Bare"', 'alt="Flammen über dem Grill und Glut neben den Peka-Glocken in der Konoba Bare"'),
    ('<figcaption>Žar i gradele</figcaption>', '<figcaption>Glut und Grill</figcaption>'),
    ('alt="Pizza iz konobe Bare, ravno iz peći"', 'alt="Pizza aus der Konoba Bare, direkt aus dem Ofen"'),
    ('<figcaption>Pizza za cijeli stol</figcaption>', '<figcaption>Pizza für den ganzen Tisch</figcaption>'),
    ('alt="Krakovi hobotnice s krumpirom izbliza, iz teće"', 'alt="Oktopusarme mit Kartoffeln aus der Nähe, aus der Pfanne"'),
    ('<figcaption>Iz teće</figcaption>', '<figcaption>Aus der Pfanne</figcaption>'),
    ('alt="Pizza s rukolom na stolu terase konobe Bare"', 'alt="Pizza mit Rucola auf einem Terrassentisch der Konoba Bare"'),
    ('<figcaption>Na terasi, uz more</figcaption>', '<figcaption>Auf der Terrasse am Meer</figcaption>'),
    ('aria-label="Video momenti iz kuhinje"', 'aria-label="Videomomente aus der Küche"'),
    ('<span class="eyebrow reveal">Iz kuhinje, uživo</span>', '<span class="eyebrow reveal">Aus der Küche, live</span>'),
    ('<h2 class="reveal">Tri kadra ispod peke</h2>', '<h2 class="reveal">Drei Szenen unter der Peka</h2>'),
    ('aria-label="Hobotnica ispod peke s krumpirom u teći, dim se diže"', 'aria-label="Oktopus unter der Peka mit Kartoffeln in der Pfanne, Rauch steigt auf"'),
    ('aria-label="Peka pod žarom, zatim meso s krumpirom u teći"', 'aria-label="Die Peka-Glocke unter Glut, dann Fleisch mit Kartoffeln in der Pfanne"'),
    ('aria-label="Slaganje hladne plate: tuna, masline, kapari i salata od hobotnice"', 'aria-label="Anrichten der kalten Platte: Thunfisch, Oliven, Kapern und Oktopussalat"'),
    ('<span class="eyebrow t-reveal">Najam broda · Bare</span>', '<span class="eyebrow t-reveal">Bootsverleih · Bare</span>'),
    ('<h2>More na dohvat ruke: najam broda</h2>', '<h2>Das Meer zum Greifen nah: Bootsverleih</h2>'),
    ('<p class="lead" data-words>Konoba Bare nije samo stol uz more.</p>', '<p class="lead" data-words>Die Konoba Bare ist mehr als ein Tisch am Meer.</p>'),
    ('<p data-words>Našim brodom Bare istražite skrivene uvale Prvića i okolnih otočića vlastitim ritmom: tiho sidrište za kupanje, ručak na pučini, zalazak daleko od gužve.</p>',
     '<p data-words>Erkunden Sie mit unserem Boot Bare die versteckten Buchten von Prvić und der umliegenden Inselchen in Ihrem eigenen Rhythmus: ein stiller Ankerplatz zum Baden, Mittagessen auf dem Wasser, ein Sonnenuntergang fern vom Trubel.</p>'),
    ('<p data-words>Detalji plovidbe i cijena: na upit, telefonom ili za stolom u konobi.</p>',
     '<p data-words>Details zur Fahrt und Preis: auf Anfrage, telefonisch oder an Ihrem Tisch in der Konoba.</p>'),
    ('class="btn-res t-reveal">Upit za najam · 022 448 094</a>', 'class="btn-res t-reveal">Mietanfrage · 022 448 094</a>'),
    ('<span class="alt-contact" data-words>Ili pitajte konobara kad sljedeći put sjednete: brod je vezan u luci, par koraka od stola.</span>',
     '<span class="alt-contact" data-words>Oder fragen Sie beim nächsten Besuch einfach den Kellner: Das Boot liegt im Hafen, ein paar Schritte vom Tisch entfernt.</span>'),
    ('alt="Brod Bare usidren u tihoj uvali otoka Prvića, kupači u tirkiznom moru uz borovu obalu"',
     'alt="Das Boot Bare vor Anker in einer stillen Bucht der Insel Prvić, Badende im türkisfarbenen Meer an der Pinienküste"'),
    ('alt="Luka Prvić Šepurina u zlatni sat: barke, kamena kuća i jedrilica u kanalu"',
     'alt="Der Hafen von Prvić Šepurine zur goldenen Stunde: Boote, ein Steinhaus und ein Segelboot im Kanal"'),
    ('alt="Brod Lara uplovljava u zalazak sunca pred Prvić Šepurinama, uz svjetionik na mulu"',
     'alt="Das Boot Lara fährt vor Prvić Šepurine in den Sonnenuntergang, vorbei am Leuchtfeuer auf der Mole"'),
    ('„Večer na Prviću ne traži ništa, samo da ostanete još malo.“',
     '„Ein Abend auf Prvić verlangt nichts von Ihnen, nur dass Sie noch ein wenig bleiben.“'),
    ('<span class="eyebrow">Kako doći</span>', '<span class="eyebrow">Anreise</span>'),
    ('<h2>Pronađite nas na otoku.</h2>', '<h2>Sie finden uns auf der Insel.</h2>'),
    ('<h3>Adresa</h3>', '<h3>Adresse</h3>'),
    ('<p data-words>Prvić Šepurine, otok Prvić<br/>Šibensko-kninska županija, Hrvatska</p>',
     '<p data-words>Prvić Šepurine, Insel Prvić<br/>Gespanschaft Šibenik-Knin, Kroatien</p>'),
    ('<h3>Brod Lara</h3>', '<h3>Bootslinie Lara</h3>'),
    ('<p data-words>Otok Prvić nema automobila. Dolazi se brodom Lara, redovnom brodskom linijom iz Šibenika i Vodica do Prvić Šepurina. Od pristaništa do konobe: kratka šetnja kalama.</p>',
     '<p data-words>Die Insel Prvić ist autofrei. Man kommt mit der Bootslinie Lara, der regulären Verbindung von Šibenik und Vodice nach Prvić Šepurine. Vom Anleger sind es nur ein paar Schritte durch die Gassen bis zur Konoba.</p>'),
    ('<h3>Radno vrijeme</h3>', '<h3>Öffnungszeiten</h3>'),
    ('<p data-words>Caffe bar: otvoren cijeli dan.<br/>Kuhinja: 14:00 – 23:00.<br/>Za veće stolove i peku javite se telefonom, uskladit ćemo i s rasporedom broda Lara.</p>',
     '<p data-words>Café-Bar: den ganzen Tag geöffnet.<br/>Küche: 14:00 – 23:00 Uhr.<br/>Für größere Tische und Peka rufen Sie uns an, wir richten uns auch nach dem Fahrplan der Lara.</p>'),
    ('<h3>Rezervacije</h3>', '<h3>Reservierungen</h3>'),
    ('<p>Telefon: <a', '<p>Telefon: <a'),
    ('style="margin-top:6px">Rezerviraj stol</a>', 'style="margin-top:6px">Tisch reservieren</a>'),
    ('<small>Klikom se učitava interaktivna karta s Google Maps servisa. Tek tada Google primi vaš IP.</small>',
     '<small>Mit einem Klick wird die interaktive Google-Maps-Karte geladen. Erst dann erhält Google Ihre IP-Adresse.</small>'),
    ('<span class="btn-res">Prikaži kartu</span>', '<span class="btn-res">Karte anzeigen</span>'),
    ("f.title='Karta — Konoba Bare, Prvić Šepurine';", "f.title='Karte — Konoba Bare, Prvić Šepurine';"),
    ('<p>Otočka konoba u Prvić Šepurinama. Riba, hobotnica i maslinovo ulje, u ritmu otoka bez automobila.</p>',
     '<p>Eine Inselkonoba in Prvić Šepurine. Fisch, Oktopus und Olivenöl, im Rhythmus einer autofreien Insel.</p>'),
    ('<h3>Stranica</h3>', '<h3>Seiten</h3>'),
    ('<a class="fl" href="#prica">Naša priča</a>', '<a class="fl" href="#prica">Unsere Geschichte</a>'),
    ('<a class="fl" href="#menu">Jelovnik</a>', '<a class="fl" href="#menu">Speisekarte</a>'),
    ('<a class="fl" href="#galerija">Galerija</a>', '<a class="fl" href="#galerija">Galerie</a>'),
    ('<a class="fl" href="#najam-broda">Najam broda</a>', '<a class="fl" href="#najam-broda">Bootsverleih</a>'),
    ('<a class="fl" href="#lokacija">Kako doći</a>', '<a class="fl" href="#lokacija">Anreise</a>'),
    ('<p style="margin-top:8px">Prvić Šepurine<br/>otok Prvić, Hrvatska</p>', '<p style="margin-top:8px">Prvić Šepurine<br/>Insel Prvić, Kroatien</p>'),
    ('<span>Stranica bez kolačića i analitike. Karta (Google Maps) učitava se tek na vaš klik.</span>',
     '<span>Keine Cookies, keine Analyse-Tools. Die Karte (Google Maps) lädt erst nach Ihrem Klick.</span>'),
]

def build(pairs, outdir):
    s = src
    # 1) putanje na assets (podmapa /en/ ili /de/)
    for old, new in COMMON_PATHS:
        s = s.replace(old, new)
    # 2) prijevodi — footer <a class="fl"> parovi moraju ići PRIJE generičkih '>Naša priča</a>' parova,
    #    zato dict redoslijed: specifični parovi su navedeni u listi, primjenjuju se redom; provjera hitova
    misses = []
    for old, new in pairs:
        if old == new:
            continue
        n = s.count(old)
        if n == 0:
            misses.append(old[:90])
            continue
        s = s.replace(old, new)
    if misses:
        print("PROMAŠENI PAROVI (%d):" % len(misses))
        for m in misses: print("  ·", m)
        sys.exit(1)
    os.makedirs(os.path.join(ROOT, outdir), exist_ok=True)
    open(os.path.join(ROOT, outdir, "index.html"), "w", encoding="utf-8").write(s)
    print(outdir + "/index.html OK,", len(s), "bytes")

# footer 'fl' linkovi prije generičkih nav parova: preuredi listu tako da parovi
# s '<a class="fl"' dođu prije parova koji počinju s '>'
def reorder(pairs):
    spec = [p for p in pairs if p[0].startswith('<a class="fl"')]
    rest = [p for p in pairs if not p[0].startswith('<a class="fl"')]
    return spec + rest

build(reorder(EN), "en")
build(reorder(DE), "de")
